ARG PHP_VERSION=7.4

FROM nginx:1.18-alpine AS NGINX

FROM composer:2.5 AS COMPOSER

FROM php:$PHP_VERSION-fpm-alpine

LABEL maintainer="php:$PHP_VERSION-fpm-alpine <decezz@qq.com>"

# 安装nginx
COPY --from=NGINX /usr/sbin/nginx /usr/sbin/nginx
COPY --from=NGINX /etc/nginx /etc/nginx
COPY --from=NGINX /usr/share/nginx/html /usr/share/nginx/html
COPY --from=NGINX /var/log/nginx /var/log/nginx
COPY --from=NGINX /var/cache/nginx /var/cache/nginx
# 切换用户 & 增加nginx启动
RUN sed -i 's/user  nginx;/user www-data;/g' /etc/nginx/nginx.conf && \
    sed -i "7i nginx" /usr/local/bin/docker-php-entrypoint


# 安装composer
COPY --from=COMPOSER /usr/bin/composer /usr/local/bin/composer


# config
RUN composer config -g repo.packagist composer https://packagist.phpcomposer.com && \
    cp -r /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini && \
    sed -i '$a error_log = /usr/share/nginx/logs/php_errors.log' /usr/local/etc/php/php.ini && \
    sed -i '$a slowlog = /usr/share/nginx/logs/php-fpm-slow.log' /usr/local/etc/php-fpm.d/www.conf

# install extensions
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories && \
    apk add --no-cache \
        git && \
    docker-php-ext-install pcntl

# install install-php-extensions
RUN curl -fsSL https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions > /usr/local/bin/install-php-extensions && \
    chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions pdo_mysql mysqli bcmath gd redis


WORKDIR /usr/share/nginx/html

CMD ["-y", "/usr/local/etc/php-fpm.conf"]
