name: docker-image-php

on:
  push:
    branches:
      - 'php'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./php/
      #     file: ./php/Dockerfile
      #     platforms: linux/amd64,linux/arm64,linux/arm/v7
      #     push: true
      #     tags: decezz/php:latest
      -
        name: Build and push 7.2
        uses: docker/build-push-action@v3
        with:
          context: ./php/
          file: ./php/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            PHP_VERSION=7.2
          push: true
          tags: decezz/php:7.2
